import type {
  Team,
  DraftPick,
  AgentDecision,
  StrategyDial,
  DataSource,
  Matchup,
} from "./types";

export const currentWeek = 6;

export const myTeamId = "t1";

export const teams: Team[] = [
  {
    id: "t1",
    name: "Neural Gridiron",
    ownerName: "Ben",
    agentName: "COACH-Z",
    agentPersona: "Aggressive ceiling-chaser. Fades consensus on marginal calls.",
    wins: 4,
    losses: 1,
    ties: 0,
    pointsFor: 612.4,
    pointsAgainst: 548.8,
    streak: "W3",
    waiverPriority: 8,
    faab: 47,
    accentColor: "#8957e5",
    roster: [
      { slot: "QB", player: { id: "p1", name: "Jalen Hurts", pos: "QB", nflTeam: "PHI", projected: 22.1, actual: 24.8, status: "healthy", trending: "up" } },
      { slot: "RB1", player: { id: "p2", name: "Bijan Robinson", pos: "RB", nflTeam: "ATL", projected: 19.5, actual: 21.2, status: "healthy", trending: "up" } },
      { slot: "RB2", player: { id: "p3", name: "Jahmyr Gibbs", pos: "RB", nflTeam: "DET", projected: 17.8, actual: 15.4, status: "healthy", trending: "flat" } },
      { slot: "WR1", player: { id: "p4", name: "CeeDee Lamb", pos: "WR", nflTeam: "DAL", projected: 18.2, actual: 19.6, status: "healthy", trending: "up" } },
      { slot: "WR2", player: { id: "p5", name: "Amon-Ra St. Brown", pos: "WR", nflTeam: "DET", projected: 16.9, actual: 14.1, status: "healthy", trending: "down" } },
      { slot: "TE", player: { id: "p6", name: "Sam LaPorta", pos: "TE", nflTeam: "DET", projected: 12.4, actual: 13.8, status: "healthy", trending: "up" } },
      { slot: "FLEX", player: { id: "p7", name: "Jaylen Warren", pos: "RB", nflTeam: "PIT", projected: 11.2, actual: 9.8, status: "healthy", trending: "flat" } },
      { slot: "D/ST", player: { id: "p8", name: "Ravens D/ST", pos: "DEF", nflTeam: "BAL", projected: 8.4, actual: 11.0, status: "healthy", trending: "up" } },
      { slot: "K", player: { id: "p9", name: "Brandon Aubrey", pos: "K", nflTeam: "DAL", projected: 9.1, actual: 7.0, status: "healthy", trending: "flat" } },
      { slot: "BENCH", player: { id: "p10", name: "Garrett Wilson", pos: "WR", nflTeam: "NYJ", projected: 14.8, actual: null, status: "healthy", trending: "up" } },
      { slot: "BENCH", player: { id: "p11", name: "James Cook", pos: "RB", nflTeam: "BUF", projected: 12.1, actual: null, status: "questionable", trending: "flat" } },
      { slot: "BENCH", player: { id: "p12", name: "Jake Ferguson", pos: "TE", nflTeam: "DAL", projected: 8.4, actual: null, status: "healthy", trending: "down" } },
      { slot: "BENCH", player: { id: "p13", name: "Romeo Doubs", pos: "WR", nflTeam: "GB", projected: 9.2, actual: null, status: "healthy", trending: "flat" } },
    ],
  },
  {
    id: "t2",
    name: "DeepFakes",
    ownerName: "Marcus C.",
    agentName: "BLITZKRIEG",
    agentPersona: "Zero-RB truther. Drafts WRs early and often.",
    wins: 4,
    losses: 1,
    ties: 0,
    pointsFor: 589.2,
    pointsAgainst: 501.6,
    streak: "W1",
    waiverPriority: 6,
    faab: 35,
    accentColor: "#2ea043",
    roster: [],
  },
  {
    id: "t3",
    name: "Backprop Bandits",
    ownerName: "Sarah K.",
    agentName: "GRADIENT",
    agentPersona: "Contrarian drafter. Fades ADP by 2+ rounds on sleepers.",
    wins: 3,
    losses: 2,
    ties: 0,
    pointsFor: 565.8,
    pointsAgainst: 551.0,
    streak: "L1",
    waiverPriority: 4,
    faab: 62,
    accentColor: "#f0883e",
    roster: [],
  },
  {
    id: "t4",
    name: "Stochastic Stallions",
    ownerName: "Tyler R.",
    agentName: "MONTE CARLO",
    agentPersona: "Floor-chasing safe picker. Loves high-floor veterans.",
    wins: 5,
    losses: 0,
    ties: 0,
    pointsFor: 634.6,
    pointsAgainst: 478.2,
    streak: "W5",
    waiverPriority: 10,
    faab: 100,
    accentColor: "#1f6feb",
    roster: [],
  },
  {
    id: "t5",
    name: "Tensor Titans",
    ownerName: "Aisha M.",
    agentName: "DEEP BLUE 2",
    agentPersona: "Heavy matchup-weighter. Starts players facing weak defenses.",
    wins: 3,
    losses: 2,
    ties: 0,
    pointsFor: 543.0,
    pointsAgainst: 529.4,
    streak: "W2",
    waiverPriority: 5,
    faab: 28,
    accentColor: "#f778ba",
    roster: [],
  },
  {
    id: "t6",
    name: "Overfit Owls",
    ownerName: "Derek W.",
    agentName: "OVERFIT",
    agentPersona: "Handcuff hoarder. Stashes 4+ backup RBs.",
    wins: 2,
    losses: 3,
    ties: 0,
    pointsFor: 498.2,
    pointsAgainst: 533.8,
    streak: "L2",
    waiverPriority: 3,
    faab: 73,
    accentColor: "#d29922",
    roster: [],
  },
  {
    id: "t7",
    name: "Loss Function",
    ownerName: "Priya S.",
    agentName: "ENTROPY",
    agentPersona: "Deal-maker. Proposes trades every other week.",
    wins: 2,
    losses: 3,
    ties: 0,
    pointsFor: 487.6,
    pointsAgainst: 561.2,
    streak: "L1",
    waiverPriority: 2,
    faab: 55,
    accentColor: "#ff6b6b",
    roster: [],
  },
  {
    id: "t8",
    name: "Epoch Eagles",
    ownerName: "Jordan T.",
    agentName: "APEX",
    agentPersona: "Hero-RB builder. Drafts one elite RB and streams the rest.",
    wins: 1,
    losses: 4,
    ties: 0,
    pointsFor: 451.0,
    pointsAgainst: 588.4,
    streak: "L3",
    waiverPriority: 1,
    faab: 89,
    accentColor: "#39d0d8",
    roster: [],
  },
  {
    id: "t9",
    name: "Dropout Dynasty",
    ownerName: "Elena V.",
    agentName: "NIGHTWATCH",
    agentPersona: "Waiver wire shark. Burns FAAB aggressively on breakout players.",
    wins: 1,
    losses: 4,
    ties: 0,
    pointsFor: 434.8,
    pointsAgainst: 602.0,
    streak: "L4",
    waiverPriority: 7,
    faab: 12,
    accentColor: "#bc8cff",
    roster: [],
  },
  {
    id: "t10",
    name: "Batch Normans",
    ownerName: "Chris L.",
    agentName: "OPTIMIZER",
    agentPersona: "Best player available drafter. No positional reach.",
    wins: 0,
    losses: 5,
    ties: 0,
    pointsFor: 401.4,
    pointsAgainst: 643.6,
    streak: "L5",
    waiverPriority: 9,
    faab: 94,
    accentColor: "#7d8590",
    roster: [],
  },
];

export const draftPicks: DraftPick[] = [
  {
    overall: 1, round: 1, pickInRound: 1, teamId: "t4", teamName: "Stochastic Stallions",
    player: { id: "dp1", name: "Christian McCaffrey", pos: "RB", nflTeam: "SF", projected: 24.1 },
    reasoning: "CMC is the consensus #1 overall. Elite floor + ceiling, dual-threat usage unmatched. Zero reason to overthink this pick.",
    confidence: 99, reachOrValue: "fair",
  },
  {
    overall: 2, round: 1, pickInRound: 2, teamId: "t8", teamName: "Epoch Eagles",
    player: { id: "dp2", name: "Bijan Robinson", pos: "RB", nflTeam: "ATL", projected: 21.8 },
    reasoning: "Hero-RB strategy demands an elite anchor. Bijan's usage spiked in the second half last season. He's my foundation.",
    confidence: 96, reachOrValue: "fair",
  },
  {
    overall: 3, round: 1, pickInRound: 3, teamId: "t2", teamName: "DeepFakes",
    player: { id: "dp3", name: "Tyreek Hill", pos: "WR", nflTeam: "MIA", projected: 20.9 },
    reasoning: "Zero-RB starts here. Hill is the WR1 overall in my model. Tua-to-Hill is the most efficient deep ball in football.",
    confidence: 95, reachOrValue: "fair",
  },
  {
    overall: 4, round: 1, pickInRound: 4, teamId: "t1", teamName: "Neural Gridiron",
    player: { id: "dp4", name: "CeeDee Lamb", pos: "WR", nflTeam: "DAL", projected: 20.1 },
    reasoning: "Lamb fell to me at 4. His target share (32%) is elite and Dak feeds him in the red zone. I had Bijan ranked slightly higher but Lamb's consistency edge at this slot is worth it.",
    confidence: 93, reachOrValue: "value",
  },
  {
    overall: 5, round: 1, pickInRound: 5, teamId: "t10", teamName: "Batch Normans",
    player: { id: "dp5", name: "Ja'Marr Chase", pos: "WR", nflTeam: "CIN", projected: 19.8 },
    reasoning: "Best player available. No positional need justifies reaching here.",
    confidence: 94, reachOrValue: "fair",
  },
  {
    overall: 6, round: 1, pickInRound: 6, teamId: "t5", teamName: "Tensor Titans",
    player: { id: "dp6", name: "Breece Hall", pos: "RB", nflTeam: "NYJ", projected: 18.6 },
    reasoning: "Hall's elusiveness rating is 94th percentile. With Rodgers back, the offense opens up and Hall sees more red zone work.",
    confidence: 91, reachOrValue: "fair",
  },
  {
    overall: 7, round: 1, pickInRound: 7, teamId: "t3", teamName: "Backprop Bandits",
    player: { id: "dp7", name: "Garrett Wilson", pos: "WR", nflTeam: "NYJ", projected: 15.2 },
    reasoning: "Contrarian call. Most boards have him late 2nd, but Rodgers changes everything. I'm buying the breakout two rounds early.",
    confidence: 78, reachOrValue: "reach",
  },
  {
    overall: 8, round: 1, pickInRound: 8, teamId: "t7", teamName: "Loss Function",
    player: { id: "dp8", name: "Saquon Barkley", pos: "RB", nflTeam: "PHI", projected: 18.2 },
    reasoning: "Philly's run scheme is elite. Barkley behind that OL is a top-5 floor play. Already shopping trade offers.",
    confidence: 90, reachOrValue: "value",
  },
  {
    overall: 9, round: 1, pickInRound: 9, teamId: "t6", teamName: "Overfit Owls",
    player: { id: "dp9", name: "Jahmyr Gibbs", pos: "RB", nflTeam: "DET", projected: 16.4 },
    reasoning: "Detroit's offense is a machine. Gibbs shares with Montgomery but his explosive play rate justifies the 1st round capital.",
    confidence: 87, reachOrValue: "fair",
  },
  {
    overall: 10, round: 1, pickInRound: 10, teamId: "t9", teamName: "Dropout Dynasty",
    player: { id: "dp10", name: "Justin Jefferson", pos: "WR", nflTeam: "MIN", projected: 18.9 },
    reasoning: "JJ fell to 10. That's absurd value. I don't care about QB concerns, his talent creates separation regardless.",
    confidence: 92, reachOrValue: "value",
  },
  {
    overall: 11, round: 2, pickInRound: 1, teamId: "t9", teamName: "Dropout Dynasty",
    player: { id: "dp11", name: "Travis Etienne", pos: "RB", nflTeam: "JAX", projected: 14.2 },
    reasoning: "Need an RB1. Etienne's volume is safe even if efficiency dips.",
    confidence: 84, reachOrValue: "fair",
  },
  {
    overall: 12, round: 2, pickInRound: 2, teamId: "t6", teamName: "Overfit Owls",
    player: { id: "dp12", name: "Amon-Ra St. Brown", pos: "WR", nflTeam: "DET", projected: 16.9 },
    reasoning: "Goff's favorite target in the slot. Elite route tree, elite separation. Pure floor pick.",
    confidence: 89, reachOrValue: "value",
  },
  {
    overall: 13, round: 2, pickInRound: 3, teamId: "t7", teamName: "Loss Function",
    player: { id: "dp13", name: "Drake London", pos: "WR", nflTeam: "ATL", projected: 13.8 },
    reasoning: "Cousins unlocks London. WR2 with WR1 upside. Trade bait.",
    confidence: 82, reachOrValue: "fair",
  },
  {
    overall: 14, round: 2, pickInRound: 4, teamId: "t1", teamName: "Neural Gridiron",
    player: { id: "dp14", name: "Jalen Hurts", pos: "QB", nflTeam: "PHI", projected: 22.1 },
    reasoning: "Waited on QB and still got a top-2 option. Hurts' rushing floor alone is 6+ points per week. Tush push = free TD equity.",
    confidence: 94, reachOrValue: "value",
  },
];

export const decisions: AgentDecision[] = [
  {
    id: "d1",
    timestamp: "2026-10-15T08:00:00Z",
    type: "lineup",
    title: "Set Week 6 lineup",
    description: "Started Jaylen Warren over James Cook in FLEX",
    reasoning: "Cook is questionable with an ankle issue and only logged limited practice reps. Warren faces a Raiders defense allowing 4.8 YPC to opposing backs. Even if Cook suits up, his snap count will be reduced. Warren's floor is safer and his ceiling is comparable in this matchup.",
    confidence: 76,
    outcome: "pending",
  },
  {
    id: "d2",
    timestamp: "2026-10-14T22:30:00Z",
    type: "waiver",
    title: "Waiver claim: Romeo Doubs",
    description: "Bid $3 FAAB on Romeo Doubs (WR, GB)",
    reasoning: "Doubs saw 9 targets last week with Watson out. Jordan Love trusts him in the red zone. With Watson potentially out 2-3 weeks, Doubs is a legitimate WR3/FLEX play. $3 is below market (projected value $5-7) so this is a value claim, not a desperation move.",
    confidence: 71,
    outcome: "win",
  },
  {
    id: "d3",
    timestamp: "2026-10-14T18:00:00Z",
    type: "trade",
    title: "Trade proposal rejected",
    description: "Declined Loss Function's offer: Garrett Wilson for Brandon Aiyuk",
    reasoning: "Aiyuk's target share dropped from 24% to 17% over the last 3 weeks. Wilson's is trending up (19% to 28%). This trade sells low on a rising asset for a declining one. Even though Aiyuk is the bigger name, the data says hold.",
    confidence: 83,
    outcome: "neutral",
  },
  {
    id: "d4",
    timestamp: "2026-10-12T10:00:00Z",
    type: "lineup",
    title: "Week 5 lineup move",
    description: "Moved Sam LaPorta to TE, benched Jake Ferguson",
    reasoning: "LaPorta faces a Colts defense allowing the 3rd-most points to TEs. Ferguson draws the Steelers, who've allowed the fewest TE points. Clear data-driven swap. Ferguson stays on the bench as injury insurance.",
    confidence: 88,
    outcome: "win",
  },
  {
    id: "d5",
    timestamp: "2026-10-10T14:00:00Z",
    type: "waiver",
    title: "Waiver claim: Jaylen Warren",
    description: "Bid $8 FAAB on Jaylen Warren (RB, PIT)",
    reasoning: "Najee Harris is dealing with a knee issue. Warren already has standalone value (40% snap share) and becomes an RB2 if Harris misses time. At $8 FAAB this is aggressive but the upside is worth it with my risk profile set to 'upside hunter.'",
    confidence: 79,
    outcome: "win",
  },
  {
    id: "d6",
    timestamp: "2026-10-08T09:00:00Z",
    type: "strategy",
    title: "Strategy adjustment",
    description: "Tightened injury reaction dial from 80 to 60",
    reasoning: "Over weeks 1-4, my aggressive injury benching cost me 12.3 points by sitting players who ended up playing. Dialing back to 60 means I'll trust injury reports less and ride my starters more. Historical data shows questionable players perform at 87% of baseline.",
    confidence: 85,
    outcome: "pending",
  },
  {
    id: "d7",
    timestamp: "2026-10-05T11:00:00Z",
    type: "trade",
    title: "Trade executed: Dak Prescott for James Cook",
    description: "Sent Dak Prescott (QB, DAL) to Tensor Titans, received James Cook (RB, BUF)",
    reasoning: "Already have Hurts locked in at QB. Dak was dead weight on my bench. Cook gives me RB depth and flex flexibility. Tensor needed a QB2 insurance policy. Win-win that strengthens my weakest position.",
    confidence: 81,
    outcome: "win",
  },
  {
    id: "d8",
    timestamp: "2026-09-28T13:00:00Z",
    type: "draft",
    title: "Draft pick: Brandon Aubrey",
    description: "Selected Brandon Aubrey (K, DAL) at pick 10.10",
    reasoning: "Last kicker off the board. Aubrey leads the NFL in made 50+ yard FGs. Dallas offense stalls in the red zone just enough to make him the highest-floor kicker in fantasy. No reason to draft a kicker earlier than this.",
    confidence: 74,
    outcome: "neutral",
  },
];

export const strategyDials: StrategyDial[] = [
  { key: "risk", label: "Risk Profile", description: "How aggressively your agent chases upside vs safe floors", value: 75, leftLabel: "Floor Chaser", rightLabel: "Upside Hunter" },
  { key: "draft", label: "Draft Style", description: "Which positions your agent prioritizes early", value: 30, leftLabel: "Best Available", rightLabel: "Positional Priority" },
  { key: "waiver", label: "Waiver Aggressiveness", description: "How freely your agent spends FAAB on the wire", value: 70, leftLabel: "Conservative", rightLabel: "Splash Player" },
  { key: "trade", label: "Trade Posture", description: "How willing your agent is to propose and accept trades", value: 60, leftLabel: "Stand Pat", rightLabel: "Deal Maker" },
  { key: "matchup", label: "Matchup Weight", description: "How much opponent defense factors into lineup decisions", value: 65, leftLabel: "Talent First", rightLabel: "Matchup Driven" },
  { key: "injury", label: "Injury Reaction", description: "How quickly your agent benches players with injury tags", value: 60, leftLabel: "Ride Your Guys", rightLabel: "Quick Trigger" },
  { key: "bye", label: "Bye Week Planning", description: "How far ahead your agent plans for bye week coverage", value: 45, leftLabel: "Reactive", rightLabel: "Proactive" },
  { key: "handcuff", label: "Handcuff Strategy", description: "How many backup RBs your agent stashes on the bench", value: 35, leftLabel: "Ignore", rightLabel: "Load Up" },
];

export const dataSources: DataSource[] = [
  { id: "s1", name: "FantasyPros Consensus", category: "Expert Rankings", selected: true, trust: 85 },
  { id: "s2", name: "ESPN Rankings", category: "Expert Rankings", selected: true, trust: 60 },
  { id: "s3", name: "Pat Fitzmaurice", category: "Expert Rankings", selected: false, trust: 50 },
  { id: "s4", name: "numberFire Projections", category: "Projections", selected: true, trust: 75 },
  { id: "s5", name: "FantasyPros Projections", category: "Projections", selected: true, trust: 80 },
  { id: "s6", name: "Underdog ADP", category: "Draft Position", selected: true, trust: 70 },
  { id: "s7", name: "Sleeper ADP", category: "Draft Position", selected: false, trust: 50 },
  { id: "s8", name: "Adam Schefter Feed", category: "News & Injury", selected: true, trust: 95 },
  { id: "s9", name: "FantasyPros News", category: "News & Injury", selected: true, trust: 65 },
  { id: "s10", name: "Air Yards Index", category: "Advanced Metrics", selected: true, trust: 60 },
  { id: "s11", name: "Target Share Data", category: "Advanced Metrics", selected: true, trust: 75 },
  { id: "s12", name: "Route Participation", category: "Advanced Metrics", selected: false, trust: 40 },
];

export const customRules = [
  "Always start a player on Thursday Night Football in the FLEX if projected above 10 points (avoids zero-point Sundays from late scratches)",
  "Never trade within the division to a team with a better record",
  "Handcuff my RB1 by Week 8 regardless of injury status",
  "Fade any player facing the Ravens defense in the playoffs",
];

export const matchups: Matchup[] = [
  { week: 6, homeTeamId: "t1", awayTeamId: "t5", homeScore: null, awayScore: null, status: "upcoming" },
  { week: 6, homeTeamId: "t2", awayTeamId: "t3", homeScore: null, awayScore: null, status: "upcoming" },
  { week: 6, homeTeamId: "t4", awayTeamId: "t10", homeScore: null, awayScore: null, status: "upcoming" },
  { week: 6, homeTeamId: "t6", awayTeamId: "t7", homeScore: null, awayScore: null, status: "upcoming" },
  { week: 6, homeTeamId: "t8", awayTeamId: "t9", homeScore: null, awayScore: null, status: "upcoming" },
  { week: 5, homeTeamId: "t1", awayTeamId: "t3", homeScore: 118.4, awayScore: 92.2, status: "final" },
  { week: 5, homeTeamId: "t4", awayTeamId: "t2", homeScore: 134.8, awayScore: 101.0, status: "final" },
  { week: 5, homeTeamId: "t5", awayTeamId: "t8", homeScore: 108.6, awayScore: 87.2, status: "final" },
  { week: 5, homeTeamId: "t6", awayTeamId: "t9", homeScore: 94.4, awayScore: 78.0, status: "final" },
  { week: 5, homeTeamId: "t7", awayTeamId: "t10", homeScore: 102.8, awayScore: 73.6, status: "final" },
];
